### ISSUE TITLE
require('Vreme') not working 

### ISSUE THREAD

**Issue by tju** [stojanovic/vreme#5]
Steps to reproduce:
- run: npm install vreme
- create new js with require('Vreme');
- run it with node
- -> "Error: Cannot find module 'Vreme'"

Managed to fix-it by changing your package.json main: to be "vreme.js" instead of "index.js"

**Comment by stojanovic** [comment]
Fixed in a4b1cbe32f54293cbce17af8ee45af8a01dd33a5 and v3.0.2 is on npm.
Thanks!

PS. Next time send PR :)
